### PR TITLE
Removes unnecessary check that actually breaks legitimate builds.

### LINKED ISSUE #72: Error when building with no resources
Building with no resources gives error: `Source files for application layer cannot be empty`

### PR DESCRIPTION
**Pull request by coollog**
Fixes #72

### CODE REVIEW

File: jib-core/src/main/java/com/google/cloud/tools/jib/cache/LayerMetadata.java [hunk 1]
```diff
@@ -43,10 +43,6 @@ static LayerMetadata from(List<Path> sourceFiles, FileTime lastModifiedTime) {
   private final FileTime lastModifiedTime;
 
   LayerMetadata(List<String> sourceFiles, FileTime lastModifiedTime) {
-    if (sourceFiles.isEmpty()) {
```
Comment (loosebazooka) [inline jib-core/src/main/java/com/google/cloud/tools/jib/cache/LayerMetadata.java]: Would allow possibly invalid apps through? All resources, no source? I mean I guess we don't need to care if the user is being insane.

Comment (coollog) [reply jib-core/src/main/java/com/google/cloud/tools/jib/cache/LayerMetadata.java]: Yeah, it would allow that, though I think our guarantee could be that the application runs in the container like it would locally.
